**load graph**

In [1]:

graph = {}
with open('out.dimacs10-polbooks', 'r') as f:
    next(f) # skip the header line
    for line in f:
        u, v = map(int, line.split())
        if u not in graph:
            graph[u] = set()
        if v not in graph:
            graph[v] = set()
        graph[u].add(v)
        graph[v].add(u) # add the reverse edge because the graph is undirected


In [2]:
print(graph)

{1: {2, 3, 4, 5, 6, 7}, 2: {1, 4, 6, 7}, 3: {8, 1, 5, 6}, 4: {1, 2, 6, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28}, 5: {32, 1, 3, 6, 7, 29, 30, 31}, 6: {1, 2, 3, 4, 5, 7, 8}, 7: {1, 2, 5, 6, 8, 11, 13, 19, 23, 26, 30}, 8: {33, 34, 3, 35, 6, 7, 15, 31}, 9: {4, 10, 11, 12, 13, 14, 15, 21, 22, 23, 24, 25, 27, 28, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46}, 10: {4, 9, 41, 12, 13, 45, 15, 47, 48, 49, 50, 51, 21, 52, 25, 28}, 11: {4, 37, 38, 7, 39, 9, 12, 13, 16, 17, 20, 53, 22, 54, 55}, 12: {4, 9, 10, 11, 13, 14, 15, 45, 47, 18, 50, 21, 22, 23, 56, 27, 28, 30}, 13: {4, 7, 9, 10, 11, 12, 14, 15, 16, 18, 19, 24, 25, 36, 37, 40, 41, 44, 46, 47, 53, 54, 55, 57, 58}, 14: {4, 36, 40, 9, 42, 43, 12, 13, 44, 47, 18, 59, 30}, 15: {33, 4, 8, 9, 10, 12, 13, 26, 27}, 16: {4, 11, 13, 17, 55}, 17: {16, 11, 4}, 18: {4, 12, 13, 14, 47}, 19: {4, 13, 7}, 20: {4, 11, 55, 56, 60}, 21: {4, 40, 9, 10, 12, 48, 49, 25, 59, 61}, 22: {4, 9, 11, 12, 24}, 23: {4, 7, 40, 9, 12, 52, 2

**degree matrix**

In [3]:
import numpy as np

size = len(graph)

degree_matrix = np.zeros((size, size))
for i, node in enumerate(graph.keys()):
       degree_matrix[i][i] = len(graph[node])


105


In [4]:
display(degree_matrix)

array([[6., 0., 0., ..., 0., 0., 0.],
       [0., 4., 0., ..., 0., 0., 0.],
       [0., 0., 4., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 3., 0., 0.],
       [0., 0., 0., ..., 0., 7., 0.],
       [0., 0., 0., ..., 0., 0., 5.]])

**adjacency matrix**

In [5]:

adjacency_matrix = np.zeros((size, size))

for i, node in enumerate(graph.keys()):
  for j in graph[node]:
      j = j-1
      adjacency_matrix[i][j] = 1
      adjacency_matrix[j][i] = 1 # add the reverse edge because the graph is undirected

In [6]:
display(adjacency_matrix)

array([[0., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# **laplacian matrix**

In [7]:
laplacian = degree_matrix - adjacency_matrix


In [8]:
print(laplacian)

[[ 6. -1. -1. ...  0.  0.  0.]
 [-1.  4.  0. ...  0.  0.  0.]
 [-1.  0.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  3.  0.  0.]
 [ 0.  0.  0. ...  0.  7.  0.]
 [ 0.  0.  0. ...  0.  0.  5.]]


In [9]:
import numpy as np

# Calculate the eigenvalues and eigenvectors of the Laplacian matrix
eigenvalues, eigenvectors = np.linalg.eig(laplacian)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Eigenvalues: [2.65816773e+01 2.60116071e+01 2.40847766e+01 2.43962850e+01
 2.34947215e+01 2.26628838e+01 2.17029098e+01 2.09656528e+01
 2.00097106e+01 1.90093933e+01 1.86947841e+01 1.74473184e+01
 1.67991787e+01 1.67246718e+01 1.57256466e+01 1.56512770e+01
 1.53728423e+01 1.40678607e+01 1.34126501e+01 1.32948518e+01
 1.28419952e+01 3.05841201e-15 1.21980488e+01 1.18840355e+01
 1.17219127e+01 3.23607315e-01 1.12873118e+01 1.10094323e+01
 7.64480671e-01 1.06334234e+01 1.01875797e+01 1.01459095e+01
 1.39014114e+00 1.60287332e+00 9.62101606e+00 1.81029903e+00
 1.89250401e+00 9.31232663e+00 9.08689727e+00 8.88542463e+00
 8.80561029e+00 2.10044318e+00 8.64016872e+00 2.17853718e+00
 2.63084779e+00 8.55184642e+00 8.45643495e+00 8.36511821e+00
 8.37970779e+00 8.17621916e+00 2.76657841e+00 7.84063007e+00
 7.79073035e+00 2.84081648e+00 2.88371446e+00 7.61646007e+00
 2.96865938e+00 2.88653383e+00 7.52065405e+00 3.09918475e+00
 7.45613397e+00 3.27347119e+00 3.33892723e+00 3.30476486e+00
 7.15655511

# **node represantation**

In [10]:
# Get the second eigenvector
second_eigenvector = eigenvectors[:, 1]

node_representations = {}


for i, node in enumerate(graph.keys()):

   node_representations[node] = second_eigenvector[i]


print(node_representations)

{1: -0.015659160740925104, 2: -0.01409616814007719, 3: 0.0016432443168877945, 4: 0.30294095445277835, 5: -0.0001205793424006359, 6: -0.016301522934494918, 7: 0.039299044181994904, 8: -0.004089185283318285, 9: -0.7002084135092014, 10: 0.07553146937632642, 11: 0.0632452661887069, 12: 0.09154212988817488, 13: -0.5892468130222152, 14: 0.04850553065406236, 15: 0.04971296863237958, 16: 0.010239616910542938, 17: -0.01635808553624942, 18: 0.007945707022543401, 19: 0.010734009716396677, 20: -0.018412898028481776, 21: 0.004637803339135259, 22: 0.00912661266507997, 23: 0.008853761547670213, 24: 0.050715263348736654, 25: 0.047235693083546845, 26: -0.025119073144921254, 27: 0.005303775428919065, 28: -0.0002666073096853844, 29: -3.151210212498907e-05, 30: -0.008142346191552626, 31: 0.001217648493715403, 32: 0.00014643271828715986, 33: -0.0023523351972703646, 34: 0.00017946933679162912, 35: 0.0002542819231376256, 36: 0.05363366707739472, 37: 0.06330489163614295, 38: 0.021436105702526843, 39: 0.029304

# **find best clustering with min cut and modularity**

In [11]:
def cut_count(graph, labels):

   num_inter_cluster_edges = 0
   for i, node in enumerate(graph.keys()):
       i += 1
       for j in graph[node]:
           if labels[i] != labels[j]:
               num_inter_cluster_edges += 1
   return num_inter_cluster_edges


In [12]:
def modularity(A, labels):


   node_degrees = np.sum(A, axis=1)


   total_edges= np.sum(node_degrees) / 2

   #edges within each cluster

   cluster_edges  = np.array([np.sum(A[labels == i] * (labels == i).T) for i in range(max(labels) + 1)])

   #edges between different clusters

   out_cluster_edges = np.sum(A * (labels[:, None] != labels[None, :]).astype(int))

   # return  sum of the squares of the ratios of the number of
   # edges within each cluster to the total number of edges,
   # minus the ratio of the number of edges between different clusters to the total number of edges
   return np.sum(cluster_edges**2 / (2 * total_edges)) - out_cluster_edges**2 / (2 * total_edges* total_edges)


In [13]:
import numpy as np

def modularity(A, labels):

   # Calculate node degrees
   node_degrees = np.sum(A, axis=1)

   # Calculate total edges
   total_edges = np.sum(node_degrees) / 2

   # Calculate edges within each cluster
   cluster_edges = np.array([np.sum(A[labels == i] * (labels == i).T) for i in range(max(labels) + 1)])

   # Calculate edges between different clusters
   out_cluster_edges = np.sum(A * (labels[:, None] != labels[None, :]).astype(int))

   #  expected edges within each cluster
   expected_in_cluster_edges = np.array([np.sum(node_degrees[labels == i] * (node_degrees[labels == i] / total_edges)) for i in range(max(labels) + 1)])

   # expected edges between different clusters
   expected_out_cluster_edges = np.sum(node_degrees * (node_degrees / total_edges)) - np.sum(expected_in_cluster_edges)

   # Calculate modularity
   modularity = (1 / (2 * total_edges)) * np.sum((cluster_edges - expected_in_cluster_edges) * (cluster_edges - expected_in_cluster_edges)) - (out_cluster_edges - expected_out_cluster_edges)**2 / (2 * total_edges * total_edges)

   return modularity


In [15]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

best_modularity = -np.inf
best_min_cut = np.inf
best_k_modularity = None
best_k_min_cut = None

for k in range(2, 11):

 # Perform KMeans clustering
 kmeans = KMeans(n_clusters=k , n_init='auto' , random_state=0)
 label_values = kmeans.fit_predict(eigenvectors)


 labels_dict = {node: label for node, label in zip(graph.keys(), label_values)}

 modularity_score = modularity(adjacency_matrix, label_values)

 # Calculate the number of inter-cluster edges
 cut = cut_count(graph, labels_dict)

# find best k for modularity
 if modularity_score > best_modularity:
    best_modularity = modularity_score
    best_k_modularity = k

# find best k for min-cut
 if cut < best_min_cut:
    best_min_cut = cut
    best_k_min_cut = k

print(f"Best k for modularity: {best_k_modularity}, Best Modularity: {best_modularity}")
print(f"Best k for min cut: {best_k_min_cut}, Best Cut: {best_min_cut}")


Best k for modularity: 6, Best Modularity: 524.1457965785816
Best k for min cut: 6, Best Cut: 180
